const ROUTES = {
  // HOME: 'Home',
  LANDINGSCREEN:'LandingScreen',
  SUBJECT_LIST:'SubjectList',
  SUBJECT_LEVEL:'SubjectLevel',
  HOME_DRAWER: 'HOME_DRAWER',
  EXAMSETS: 'ExamSets',
  REPORT: 'Report',
  SCOREBOARD: 'ScoreBoard',
  ANSWERSHEET: 'AnswerSheet',
  PREV_YEAR_ANSWERSHEET : 'PrevYearAnswersheet',
  VIDEOTUTORIALSCREEN: 'VideoScreen',
  INTROVIDEOSCREEN:"IntroVideoScreen",
  SOLUTIONSCREEN: 'SolutionScreen',
  NOTIFICATION: 'Notification',
  HOMETAB: 'HomeTab',
  KIDS_PROFILE: 'Kids_Profile',
  CONTACT_US: 'ContactUs',
  PROFILE_TAB: 'profile_tab',
  NOTIFICATION_TAB: 'notification_tab',
  REPORTS_TAB: 'Reports_tab',
  MAINTENANCE:'MaintenanceModal',
  EXPIREDTOKENSCREEN:'ExpiredTokenScreen',
  STORE_TAB: 'Store_tab',
  MYSTORE: 'MyStore',
  ADDRESSSCREEN:'AddressScreen',
  PRODUCT_LIST:'ProductList',
  PROFILE: 'Profile',
  PROFILE_DETAILS: 'Profile_details',
  USERHOME: 'UserHome',
  SUBJECTSDETAILS: 'SubjectsDetails',
  THANKS:'Thanks',
  ORDERLIST:'OrderList',
  ORDERDETAILS:'OrderDetails',

  PREV_QUESTION: 'PrevYearQues',
  PREV_SUB_LIST:"PrevSubjectList",
  PROB_SUB_LIST: 'ProbSubjectList',
  PROBABLE_QUESTION: 'ProbQuestion',

  MOCKTESTS: 'MockTests',
  // PREMOCKTEST:"PrevMockTest",
  PREVMOCKTEST:"PrevMockTest",
  PROBABLEMOCKTEST:"ProbableMockTest",
  YOUTUBEVIDEO:'Youtubevideo',
  LIVECLASSLIST:'LiveClassList',
  USERPROFILE: 'UserProfile',
  KIDSDETAILS: 'Kid_Detail',
  TERMCONDITION: 'TermAndConditions',
  PREMIUMACCESS: 'PremiumAccess',
  PREMIUMPURCHASE: 'PremiumPurchase',
  NOTIFICATIONMOCKTEST:"NotificationMockTest",
  NOTIFICATIONSCOREBOARD:'NotificationScoreBoard',
  NOTIFICATIONQUESTION:"NotificationQuestion",
  CHANGEPASSWORD:'ChangePassword',
  FORGETPASSWORDOTP:'ForgetPasswordOtp',
  PROGRESSCHART:'ProgressChart',
  PRODUCTDETAILS:'ProductDetails',
  MYCART:'MyCart',
  EDITPROFILE:'EditProfile',
  VIDEOSOLUTIONSCREEN:'VideoSolutionScreen',
  YOUTUBELIST:'YoutibeList',
  REVIEWS: 'Reviews',
  DETAILS: 'Details',
  TOPICDETAILS:'TopicDetails',
  CONTENTDETAILS:'ContentDetails',
  LEVELCOMPLETED: 'LevelCompleted',
};

export default ROUTES;
